import { Topbar, Footer, Sidebar } from "@/design-system/layout";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div>
        <Sidebar />
        <div className="lg:ms-64 ms-0">
          <Topbar />
          {children}
        </div>
      </div>

      <Footer />
    </div>
  );
}
