import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { interLocal } from "./font";
import { TooltipProvider } from "@/design-system/Atoms/Tooltip";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interLocal.className} ${interLocal.variable}antialiased bg-gray-100 overflow-hidden mr-0`}
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
