import { SidebarProvider } from "@/components/molecules/sidebar/sidebar";
import { Footer, Topbar } from "@/shared/layout";
import SidebarMenu from "@/shared/layout/Sidebar";
import sidebarGroups from "@/shared/layout/sidebarGroups";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="lg:ms-64 ms-0">
        {" "}
        <Topbar />
        <div className="px-8 py-8">{children}</div>
      </div>

      <SidebarProvider>
        <SidebarMenu groups={sidebarGroups} />
      </SidebarProvider>
      <Footer />
    </div>
  );
}
